message_converter:
  ros__parameters:
    contactdetection_topic: "/state_estimator/contact_detection"
    joint_states_topic: "/joint_states"
    blind_pub_topic: "/dls2/blind_state"
    joints_order: [
       FL_shoulder_joint,
       FL_thigh_joint,
       FL_calf_joint,
       FR_shoulder_joint,
       FR_thigh_joint,
       FR_calf_joint,
       BL_shoulder_joint,
       BL_thigh_joint,
       BL_calf_joint,
       BR_shoulder_joint,
       BR_thigh_joint,
       BR_calf_joint
    ]
