message_converter:
  ros__parameters:
    contactdetection_topic: "/state_estimator/contact_detection"
    joint_states_topic: "/joint_states"
    blind_pub_topic: "/dls2/blind_state"
    joints_order: [
       FL_shoulder_joint,
       FL_upper_leg_joint,
       FL_lower_leg_joint,
       FR_shoulder_joint,
       FR_upper_leg_joint,
       FR_lower_leg_joint,
       BL_shoulder_joint,
       BL_upper_leg_joint,
       BL_lower_leg_joint,
       BR_shoulder_joint,
       BR_upper_leg_joint,
       BR_lower_leg_joint
    ]