message_converter:
  ros__parameters:
    contactdetection_topic: "/state_estimator/contact_detection"
    joint_states_topic: "/joint_states"
    pub_topic: "/blind_state_topic"
    sync_tolerance_ms: 200